version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=password
      - xpack.security.dls_fls.enabled=true
      - xpack.security.authc.token.enabled=true
      - xpack.security.authc.realms.native.native1.order=1
      - xpack.security.authc.realms.oidc.oidc1.order=2
      - xpack.security.authc.realms.oidc.oidc1.rp.client_id=kibana
      - xpack.security.authc.realms.oidc.oidc1.rp.response_type=code
      - xpack.security.authc.realms.oidc.oidc1.rp.redirect_uri=http://kibana:5601/api/security/oidc/callback
      - xpack.security.authc.realms.oidc.oidc1.rp.post_logout_redirect_uri=https://kibana:5601/login?msg=LOGGED_OUT
      - xpack.security.authc.realms.oidc.oidc1.rp.requested_scopes=openid
      - xpack.security.authc.realms.oidc.oidc1.op.issuer=http://keycloak:8080/auth/realms/elasticsearch
      - xpack.security.authc.realms.oidc.oidc1.op.authorization_endpoint=http://keycloak:8080/auth/realms/elasticsearch/protocol/openid-connect/auth
      - xpack.security.authc.realms.oidc.oidc1.op.token_endpoint=http://keycloak:8080/auth/realms/elasticsearch/protocol/openid-connect/token
      - xpack.security.authc.realms.oidc.oidc1.op.jwkset_path=/usr/share/elasticsearch/data/jwkset.json
      - xpack.security.authc.realms.oidc.oidc1.op.userinfo_endpoint=http://keycloak:8080/auth/realms/elasticsearch/protocol/openid-connect/userinfo
      - xpack.security.authc.realms.oidc.oidc1.op.endsession_endpoint=http://keycloak:8080/auth/realms/elasticsearch/protocol/openid-connect/logout
      - xpack.security.authc.realms.oidc.oidc1.claims.principal=sub
      - xpack.security.authc.realms.oidc.oidc1.claims.groups=groups
      - xpack.security.authc.realms.jwt.jwt1.order=3
      - xpack.security.authc.realms.jwt.jwt1.client_authentication.type=none
      - xpack.security.authc.realms.jwt.jwt1.allowed_issuer="http://keycloak:8080/auth/realms/elasticsearch"
      - xpack.security.authc.realms.jwt.jwt1.allowed_audiences="account"
      - xpack.security.authc.realms.jwt.jwt1.allowed_signature_algorithms=[RS256,HS256]
      - xpack.security.authc.realms.jwt.jwt1.pkc_jwkset_path=/usr/share/elasticsearch/data/jwkset.json
      - xpack.security.authc.realms.jwt.jwt1.claims.principal=sub
      - xpack.security.authc.realms.jwt.jwt1.claims.groups=groups
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./volumes/elasticsearch-data:/usr/share/elasticsearch/data
#      - ./volumes/elasticsearch-config/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.2
    restart: always
    volumes:
      - ./volumes/kibana-config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    command: 
      - "-b 0.0.0.0"
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./volumes/postgres-init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
